services:
  - type: web
    name: plant-disease-detector
    env: python
    buildCommand: "./setup.sh"
    startCommand: "streamlit run main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
